name: point_plus_v2
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  image_picker:
  curved_navigation_bar:
  flutter:

    sdk: flutter

  cupertino_icons: ^0.1.2
  qr_flutter: ^3.2.0
  font_awesome_flutter: ^8.7.0
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+4
  rflutter_alert: ^1.0.3
  flutter_datetime_picker: ^1.3.2
  firebase_storage: ^3.1.1
  qrscan: ^0.2.17
  image_gallery_saver: ^1.2.2
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Mali
      fonts:
        - asset: assets/fonts/Mali-Regular.ttf
